// <auto-generated />
using System;
using GameServer.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameServer.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Domain.Battle.BattleResult", b =>
                {
                    b.Property<string>("BattleResultId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BossDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationTurns")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PetInstanceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RewardSummary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("BattleResultId");

                    b.HasIndex("PlayerId", "CompletedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_BattleResult_PlayerId_CompletedAt");

                    b.ToTable("BattleResult", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Bosses.BossDefinition", b =>
                {
                    b.Property<string>("BossDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BossId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("Identity");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<string>("PassiveDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SkillDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("BossDefinitionId");

                    b.HasIndex("BossId")
                        .IsUnique()
                        .HasDatabaseName("IX_BossDefinition_Identity");

                    b.ToTable("BossDefinition", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Cards.CardDefinition", b =>
                {
                    b.Property<string>("CardDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("EffectDefinition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LoadoutCopyLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PowerCost")
                        .HasColumnType("integer");

                    b.HasKey("CardDefinitionId");

                    b.ToTable("CardDefinition", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Cards.PlayerUnlockedCard", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CardDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PlayerId", "CardDefinitionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerUnlockedCard", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Pets.Pet", b =>
                {
                    b.Property<string>("PetInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PetDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Star")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("XP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PetInstanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Pet", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pet_Level_Range", "\"Level\" >= 1 AND \"Level\" <= 50");

                            t.HasCheckConstraint("CK_Pet_Star_Range", "\"Star\" >= 1 AND \"Star\" <= 5");

                            t.HasCheckConstraint("CK_Pet_XP_Range", "\"XP\" >= 0 AND \"XP\" <= 4900");
                        });
                });

            modelBuilder.Entity("GameServer.Domain.Pets.PetDefinition", b =>
                {
                    b.Property<string>("PetDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PassiveId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PassiveThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("SignatureSkillCardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PetDefinitionId");

                    b.ToTable("PetDefinition", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Players.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("XP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PlayerId");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("Player", null, t =>
                        {
                            t.HasCheckConstraint("CK_Player_Level_Range", "\"Level\" >= 1 AND \"Level\" <= 50");

                            t.HasCheckConstraint("CK_Player_XP_NonNegative", "\"XP\" >= 0");
                        });
                });

            modelBuilder.Entity("GameServer.Domain.Relics.Relic", b =>
                {
                    b.Property<string>("RelicInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RelicDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RelicInstanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Relic", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Relics.RelicDefinition", b =>
                {
                    b.Property<string>("RelicDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Condition")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EffectDefinition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RelicDefinitionId");

                    b.ToTable("RelicDefinition", (string)null);
                });

            modelBuilder.Entity("GameServer.Domain.Battle.BattleResult", b =>
                {
                    b.HasOne("GameServer.Domain.Bosses.BossDefinition", null)
                        .WithMany()
                        .HasForeignKey("BossDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Domain.Pets.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Domain.Cards.PlayerUnlockedCard", b =>
                {
                    b.HasOne("GameServer.Domain.Cards.CardDefinition", null)
                        .WithMany()
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Domain.Pets.Pet", b =>
                {
                    b.HasOne("GameServer.Domain.Pets.PetDefinition", null)
                        .WithMany()
                        .HasForeignKey("PetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Domain.Pets.PetDefinition", b =>
                {
                    b.HasOne("GameServer.Domain.Cards.CardDefinition", null)
                        .WithMany()
                        .HasForeignKey("SignatureSkillCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Domain.Relics.Relic", b =>
                {
                    b.HasOne("GameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Domain.Relics.RelicDefinition", null)
                        .WithMany()
                        .HasForeignKey("RelicDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
