namespace GameServer.Domain.Match3;

/// <summary>
/// The resources one committed Swap's cleared Gems generated
/// (<c>COMBAT_RULES.md</c> §2, <c>GAME_RULES.md</c> §17 step 12).
///
/// <code>
/// ResourceGeneration
/// ├── BaseDamagePool     ATK Gems    +10 each   × tier   (COMBAT_RULES.md §2)
/// ├── DefensePool        DEF Gems    +5  each   × tier
/// ├── HealPool           HP Gems     +20 each   × tier
/// └── Power              POWER Gems  +10 each   × tier
/// </code>
///
/// <b>This is Transient Resolution State</b> (<c>GAME_STATE.md</c> §3): it exists
/// only for the duration of resolving one Swap and is consumed by the downstream
/// resolution steps of the same resolution (13–17). It is <b>not</b> a
/// <c>BattleState</c> or <c>PlayerState</c> field, it is never serialized, never
/// written to Redis, and never delivered on the wire.
///
/// <b>Three of its four members are transient by design, not by omission.</b>
/// Only <c>Power</c> has a documented persistent home — <c>PlayerState.Power</c>
/// (<c>GAME_STATE.md</c> §2.2, <c>COMBAT_RULES.md</c> §1.1) — so this stage writes
/// its <see cref="Power"/> into that state and leaves the other three here.
/// <c>COMBAT_RULES.md</c> §3 step 1's "ATK-Gem-generated damage pool <b>for this
/// action</b>" is scoped to one action by its own wording, and Defense is read
/// per damage instance by §3.2's mitigation formula; neither is a persistent
/// stat. Adding them to <c>PlayerState</c> would extend a closed field list
/// (<c>GAME_STATE.md</c> §2.2) that no rule asks this stage to extend.
///
/// <b>The pools accumulate across every pass of the Swap</b>
/// (<c>MATCH3_RULES.md</c> §5.7 item 7): each pass's consumed cells generate once,
/// at that pass's tiers, and the Swap's total is the sum. No "cascade bonus"
/// multiplier exists in MVP.
/// </summary>
/// <param name="BaseDamagePool">
/// The ATK-Gem damage generated by this Swap, in absolute damage points. It feeds
/// the Damage Pipeline's Base Damage step for this action
/// (<c>COMBAT_RULES.md</c> §3 step 1). It is <b>not</b> <c>PlayerState.ATK</c>,
/// which is the persistent attack stat of §1.1 — this is the transient output the
/// ATK Gems contributed on top of it.
/// </param>
/// <param name="DefensePool">
/// The Defense generated by this Swap's DEF Gems. It is separate from
/// <c>PlayerState.DEF</c>, the persistent stat the mitigation formula reads
/// (<c>COMBAT_RULES.md</c> §3.2); this pool is what the DEF Gems contributed.
/// </param>
/// <param name="HealPool">
/// The healing generated by this Swap's HP Gems, consumed by the player-effects
/// step (<c>COMBAT_RULES.md</c> §4).
/// </param>
/// <param name="Power">
/// The Power generated by this Swap's POWER Gems, before the 0–100 clamp
/// (<c>COMBAT_RULES.md</c> §2, <c>GAME_RULES.md</c> §12). The clamp belongs to
/// the persistent write, and is applied by
/// <see cref="ResourceGenerator.ApplyPower"/> so the delta reported in
/// <c>PowerChanged</c> remains the clamped one.
/// </param>
/// <param name="ClearedGemCounts">
/// How many cells of each Gem type this Swap cleared, over the union of every
/// pass's cleared cells (<c>MATCH3_RULES.md</c> §5.8.2). This is the accumulation
/// the pools above are computed from, surfaced so a caller or a test can read
/// what was cleared without re-deriving it from the pools.
/// </param>
public readonly record struct ResourceGeneration(
    int BaseDamagePool,
    int DefensePool,
    int HealPool,
    int Power,
    ClearedGemCounts ClearedGemCounts)
{
    /// <summary>
    /// The generation of a Swap that cleared nothing — every pool at zero
    /// (<c>MATCH3_RULES.md</c> §4.3 item 4).
    /// </summary>
    public static ResourceGeneration None => new(0, 0, 0, 0, ClearedGemCounts.None);

    /// <summary>True when no resource of any kind was generated.</summary>
    public bool IsEmpty =>
        BaseDamagePool == 0 && DefensePool == 0 && HealPool == 0 && Power == 0;
}

/// <summary>
/// The number of cleared cells of each Gem type
/// (<c>MATCH3_RULES.md</c> §1.1, §5.8.2 item 5).
///
/// A cleared cell is counted once however many shapes or effects named it:
/// accounting is by the <b>union</b> of a pass's cleared cells, never the sum of
/// the effects' sizes (<c>MATCH3_RULES.md</c> §5.8.2 items 1–2, 5).
/// </summary>
/// <param name="Atk">Cleared ATK Gems.</param>
/// <param name="Def">Cleared DEF Gems.</param>
/// <param name="Hp">Cleared HP Gems.</param>
/// <param name="Power">Cleared POWER Gems.</param>
public readonly record struct ClearedGemCounts(int Atk, int Def, int Hp, int Power)
{
    /// <summary>No cleared cells.</summary>
    public static ClearedGemCounts None => new(0, 0, 0, 0);

    /// <summary>The total number of cleared cells across all four types.</summary>
    public int Total => Atk + Def + Hp + Power;

    /// <summary>The count for one Gem type.</summary>
    public int For(GemType type) => type switch
    {
        GemType.Atk => Atk,
        GemType.Def => Def,
        GemType.Hp => Hp,
        GemType.Power => Power,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Not a documented Gem type."),
    };

    /// <summary>This count with one cell of <paramref name="type"/> added.</summary>
    public ClearedGemCounts Increment(GemType type) => type switch
    {
        GemType.Atk => this with { Atk = Atk + 1 },
        GemType.Def => this with { Def = Def + 1 },
        GemType.Hp => this with { Hp = Hp + 1 },
        GemType.Power => this with { Power = Power + 1 },
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Not a documented Gem type."),
    };
}

/// <summary>
/// Resource Generation — <c>GAME_RULES.md</c> §17 step 12, the conversion of a
/// committed Swap's cleared Gems into the documented resource pools
/// (<c>COMBAT_RULES.md</c> §2).
///
/// <code>
/// Swap → Match Detection → Cascade Resolution → Cleared Gems
///                                             → Resource Generation → PlayerState
/// </code>
///
/// <b>Its persistent outputs are written by this type.</b> Two of the four
/// generated pools have a documented persistent home on <c>PlayerState</c>, and
/// each is written by the one method that owns it: <c>Power</c> by
/// <see cref="ApplyPower"/> (<c>GAME_RULES.md</c> §17 steps 12–13) and the
/// HealPool by <see cref="ApplyHeal"/> (§17 step 14, <c>COMBAT_RULES.md</c> §4
/// item 1). Base Damage Pool and Defense Pool deliberately reach no state —
/// <c>COMBAT_RULES.md</c> §3's Damage Pipeline, which consumes them, is a separate
/// stage.
///
/// <b>Rates.</b> The per-Gem base outputs are <c>COMBAT_RULES.md</c> §2's table:
///
/// <code>
/// ATK Gem    +10 Base Damage
/// DEF Gem    +5  Defense pool
/// HP Gem     +20 Heal pool
/// POWER Gem  +10 Power
/// </code>
///
/// <b>Tiers.</b> The §2 multiplier of the shape the Gems were consumed by applies
/// to each Gem's base output, per Gem consumed in that match. §2 owns those
/// values and states it is the sole source of truth for match-tier output; they
/// are read from <see cref="MatchTierMultipliers"/> and are not restated here.
///
/// <b>Which cells generate, and how often.</b> Owned by <c>MATCH3_RULES.md</c>
/// §5.7 and §5.8.2: once per unique cleared cell, over the union. Overlapping
/// effects therefore produce no double resources (<c>§5.8.2 item 2</c>).
///
/// <b>Which tier a cleared cell generates at.</b> A cell is consumed either as a
/// member of a Match shape — and then it generates at <b>that shape's</b> tier —
/// or by a Special Gem activation, and then it generates at the base rate because
/// an activation is not a Match and has no tier (<c>COMBAT_RULES.md</c> §2
/// item 1, <c>MATCH3_RULES.md</c> §5.7 item 6). A Special Gem's creating Match
/// applies its own tier to its own consumed Gems exactly once, and the tier is
/// never applied a second time when the Special Gem later activates
/// (<c>COMBAT_RULES.md</c> §2 item 2, <c>MATCH3_RULES.md</c> §5.5.4 item 5).
///
/// <b>Determinism.</b> This conversion is a pure function of the cleared cells
/// and their tiers: it draws no RNG, reads no wall clock, and depends on no
/// enumeration order (<c>MATCH3_RULES.md</c> §7.2, <c>AGENTS.md</c> §11). The same
/// resolution always produces the same pools.
/// </summary>
public static class ResourceGenerator
{
    /// <summary>
    /// The documented per-Gem base output of a Gem type at the Match-3 tier
    /// (<c>COMBAT_RULES.md</c> §2).
    /// </summary>
    /// <param name="type">The Gem type of one consumed cell.</param>
    /// <returns>The base output in the pool that Gem type feeds.</returns>
    public static int BaseOutputFor(GemType type) => type switch
    {
        GemType.Atk => AtkGemBaseDamage,
        GemType.Def => DefGemBaseDefense,
        GemType.Hp => HpGemBaseHeal,
        GemType.Power => PowerGemBasePower,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Not a documented Gem type."),
    };

    /// <summary>
    /// <c>ATK Gem → +10 Base Damage</c> (<c>COMBAT_RULES.md</c> §2).
    /// </summary>
    public const int AtkGemBaseDamage = 10;

    /// <summary>
    /// <c>DEF Gem → +5 Defense pool</c> (<c>COMBAT_RULES.md</c> §2).
    /// </summary>
    public const int DefGemBaseDefense = 5;

    /// <summary>
    /// <c>HP Gem → +20 Heal pool</c> (<c>COMBAT_RULES.md</c> §2).
    /// </summary>
    public const int HpGemBaseHeal = 20;

    /// <summary>
    /// <c>POWER Gem → +10 Power</c> (<c>COMBAT_RULES.md</c> §2).
    /// </summary>
    public const int PowerGemBasePower = 10;

    /// <summary>
    /// The documented Power range's ceiling (<c>GAME_RULES.md</c> §12:
    /// "Range: 0–100"; <c>COMBAT_RULES.md</c> §1.1).
    ///
    /// §12 states Power "must never exceed the configured maximum unless an
    /// explicit future mechanic allows it". No such mechanic exists, so the write
    /// of a generated Power value is capped here.
    /// </summary>
    public const int MaxPower = 100;

    /// <summary>
    /// The documented Power range's floor (<c>GAME_RULES.md</c> §12).
    ///
    /// Generation never decreases Power, so this floor is not reached by this
    /// stage; it is applied by <see cref="ApplyPower"/> so that the one operation
    /// that writes the persistent value enforces the whole documented range
    /// rather than half of it.
    /// </summary>
    public const int MinPower = 0;

    /// <summary>
    /// Generates the resources of one committed Swap from its resolved passes
    /// (<c>GAME_RULES.md</c> §17 step 12, <c>COMBAT_RULES.md</c> §2).
    ///
    /// <code>
    /// for each pass, in the resolution's own order          MATCH3_RULES.md §4.2
    ///     matched cells        → that shape's tier         §5.5.2, §5.5.4 item 5
    ///     activation cells     → the base rate (1.0×)      §5.7 item 6
    ///     a cell cleared twice → counted once              §5.8.2 items 2, 6
    ///     pools += base output × tier multiplier
    /// </code>
    ///
    /// <b>Union, not per-effect sums.</b> A pass's cleared cells are the union of
    /// its matched cells and every activation and chain cell, each once
    /// (<c>MATCH3_RULES.md</c> §5.8.2 item 5). A cell named by two effects
    /// generates once (<c>§5.8.2 items 2, 6</c>), so the pools are computed over
    /// the union and never by adding up per-effect totals.
    ///
    /// <b>Tier precedence for a shared cell.</b> Where an activation cleared a
    /// cell that a Match of the same pass also consumed, the cell is a member of
    /// that Match and generates at the Match's tier: the matched sub-step is
    /// resolved first (<c>MATCH3_RULES.md</c> §3.3 item 3 reports the matched
    /// cells first) and a cell already accounted for is not re-accounted at the
    /// base rate.
    ///
    /// <b>Nothing is multiplied twice.</b> The tier multiplier is applied once per
    /// consumed cell, at the tier of the shape that consumed it; a shape
    /// qualifying at more than one tier still counts once, at its own single tier
    /// (<c>MATCH3_RULES.md</c> §5.4 item 6). No cascade multiplier is applied: a
    /// Cascade is not a multiplier and does not aggregate passes
    /// (<c>§5.7 item 7</c>).
    /// </summary>
    /// <param name="resolution">
    /// The committed Swap's resolution, whose passes carry the cleared cells, each
    /// with its Gem type and the tier it generates at
    /// (<c>MATCH3_RULES.md</c> §5.8.2 item 5).
    /// </param>
    /// <returns>
    /// The Swap's generated pools and the cleared-cell counts they were computed
    /// from. A resolution with no passes generates nothing.
    /// </returns>
    public static ResourceGeneration Generate(CascadeResolver.CascadeResult resolution)
    {
        var counts = ClearedGemCounts.None;
        var baseDamage = 0;
        var defense = 0;
        var heal = 0;
        var power = 0;

        foreach (var pass in resolution.Passes)
        {
            // §5.8.2 item 5: one entry per cleared cell, ascending index, carrying
            // the cell's type and the tier it generates at.
            foreach (var cell in pass.ClearedGems)
            {
                var baseOutput = BaseOutputFor(cell.GemType);
                var numerator = MatchTierMultipliers.NumeratorFor(cell.Tier);

                // COMBAT_RULES.md §2: the tier multiplier is applied to the base
                // output, per Gem consumed in that match. The division is exact
                // for every documented multiplier because each is a multiple of
                // 1/Denominator; the numerator is applied before the division so
                // no intermediate value is rounded.
                var generated = (baseOutput * numerator) / MatchTierMultipliers.Denominator;

                switch (cell.GemType)
                {
                    case GemType.Atk:
                        baseDamage += generated;
                        break;
                    case GemType.Def:
                        defense += generated;
                        break;
                    case GemType.Hp:
                        heal += generated;
                        break;
                    case GemType.Power:
                        power += generated;
                        break;
                    default:
                        throw new ArgumentOutOfRangeException(
                            nameof(resolution), cell.GemType, "Not a documented Gem type.");
                }

                counts = counts.Increment(cell.GemType);
            }
        }

        return new ResourceGeneration(baseDamage, defense, heal, power, counts);
    }

    /// <summary>
    /// Writes generated Power into the player's persistent state, clamped to the
    /// documented 0–100 range (<c>COMBAT_RULES.md</c> §2, <c>GAME_RULES.md</c>
    /// §12).
    ///
    /// <code>
    /// new Power = clamp(previous Power + generated Power, 0, 100)
    /// </code>
    ///
    /// Only <c>Power</c> changes. The other <c>PlayerState</c> fields — including
    /// the Match and Combo values this stage does not own — are carried across
    /// unchanged, because the write-back replaces the state wholesale
    /// (<c>GAME_STATE.md</c> §5.1).
    ///
    /// The clamp is applied here, at the single point the persistent value is
    /// written, rather than to the transient <see cref="ResourceGeneration.Power"/>:
    /// the pool stays the amount the Swap generated, while the state holds the
    /// amount in force. A gain that the cap absorbs is visible as a delta of less
    /// than the pool.
    /// </summary>
    /// <param name="previous">The player's state before this Swap's generation.</param>
    /// <param name="generation">The Swap's generated resources.</param>
    /// <returns>
    /// The state this stage leaves: <paramref name="previous"/> with its
    /// <c>Power</c> incremented by the generated amount and clamped to 0–100.
    /// </returns>
    public static Battle.PlayerState ApplyPower(
        Battle.PlayerState previous,
        ResourceGeneration generation)
    {
        var updated = previous.Power + generation.Power;

        if (updated > MaxPower)
        {
            updated = MaxPower;
        }
        else if (updated < MinPower)
        {
            updated = MinPower;
        }

        return previous with { Power = updated };
    }

    /// <summary>
    /// Resolves the player effects of one committed Swap: applies the HealPool the
    /// original HP Gems generated to the player's persistent HP
    /// (<c>GAME_RULES.md</c> §17 step 14, <c>COMBAT_RULES.md</c> §4 item 1).
    ///
    /// <code>
    /// new HP = min(previous HP + generation.HealPool, MaxHP)
    /// </code>
    ///
    /// <b>The ceiling is MaxHP, and overheal is discarded.</b> §4 item 1: "Heal
    /// effects restore HP up to Max HP; overheal is discarded unless a Relic
    /// explicitly grants overheal/temp-HP." No Relic grants it in MVP (§4 item 4
    /// notes Heal modifiers exist but none is implemented), so the clamp is the
    /// whole of the rule and the discarded excess is stored nowhere: it is not
    /// carried into a later Swap, and it is not written to any other field.
    ///
    /// <b>HP has no documented floor applied here.</b> §4 item 1 bounds healing
    /// from above only, and this step only ever <i>adds</i> a non-negative pool, so
    /// HP can never be driven below the value the Damage Pipeline left it at
    /// (<c>COMBAT_RULES.md</c> §3 owns damage, which is not this stage). A
    /// <c>HealPool</c> of <c>0</c> — the ordinary case of a Swap that cleared no HP
    /// Gem — therefore leaves HP exactly unchanged, whatever it was.
    ///
    /// <b>No event.</b> Healing is a state-only change: <c>GAME_EVENTS.md</c> §2 has
    /// no heal event, so this step emits nothing and adds no
    /// <c>BattleEventType</c> member. The new HP is delivered, if at all, as state
    /// — adding it to the wire is a protocol change owned by its own task
    /// (<c>SIGNALR_PROTOCOL.md</c> §4.2).
    ///
    /// <b>No RNG and no second input.</b> The write is a pure function of the
    /// previous state and the pool the resolution already generated: it draws
    /// nothing, reads no clock, and re-derives nothing from the board
    /// (<c>MATCH3_RULES.md</c> §7.2, <c>AGENTS.md</c> §11). The pool is <b>not</b>
    /// scaled by the Heal tier again — the match-tier multiplier was applied once,
    /// per consumed Gem, when the pool was generated (<c>COMBAT_RULES.md</c> §2).
    ///
    /// <b>The pool is transient and stays on the resolution.</b> Reading it here
    /// does not move it: <c>HealPool</c> remains Transient Resolution State
    /// (<c>GAME_STATE.md</c> §3) on <c>SwapExecutionResult.Resources</c>, and is not
    /// added to <c>PlayerState</c> or <c>BattleState</c>.
    ///
    /// <b>Only HP changes.</b> Every other <c>PlayerState</c> field — including
    /// <c>Power</c>, which <see cref="ApplyPower"/> owns, and the Match/Combo
    /// values the accounting owns — is carried across unchanged, because the
    /// write-back replaces the state wholesale (<c>GAME_STATE.md</c> §5.1).
    /// </summary>
    /// <param name="previous">
    /// The player's state before this Swap's healing — the source of the current
    /// <c>HP</c>, of the <c>MaxHP</c> that bounds it, and of every field this step
    /// does not own.
    /// </param>
    /// <param name="generation">
    /// The Swap's generated resources, whose <see cref="ResourceGeneration.HealPool"/>
    /// is the healing to apply.
    /// </param>
    /// <returns>
    /// The state this step leaves: <paramref name="previous"/> with its <c>HP</c>
    /// increased by the HealPool and clamped to <c>MaxHP</c>.
    /// </returns>
    public static Battle.PlayerState ApplyHeal(
        Battle.PlayerState previous,
        ResourceGeneration generation)
    {
        var healed = previous.HP + generation.HealPool;

        // COMBAT_RULES.md §4 item 1: heal effects restore HP "up to Max HP", so a
        // heal that lands exactly on MaxHP is not reduced and one that would pass it
        // stops there.
        if (healed > previous.MaxHP)
        {
            healed = previous.MaxHP;
        }

        return previous with { HP = healed };
    }
}
