<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\GameServer.Application\GameServer.Application.csproj" />
    <ProjectReference Include="..\GameServer.Infrastructure\GameServer.Infrastructure.csproj" />
    <ProjectReference Include="..\GameServer.Shared\GameServer.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
